# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: ruby:2.3

variables:
  S3_BUCKET_STAGING: ""
  S3_BUCKET_PRODUCTION: ""

stages:
  - build
  - deploy

cache:
  paths:
  - vendor
  - public

#build:
#  stage: build
#  script:
#  - rm -Rf public
#  - apt-get update -yqqq
#  - apt-get install -y nodejs
#  - bundle install --path vendor
#  - bundle exec middleman build --build-dir=public --clean

#staging:
#  stage: deploy
#  image: python:latest
#  script:
#  - apt-get update -yqqq
#  - pip install awscli
#  - aws s3 sync --sse --delete public s3://$S3_BUCKET_STAGING/ --acl public-read
#  environment:
#    name: staging
#  only:
#  - develop

#production:
#  stage: deploy
#  image: python:latest
#  script:
#  - apt-get update -yqqq
#  - pip install awscli
#  - aws s3 sync --sse --delete public s3://$S3_BUCKET_PRODUCTION/ --acl public-read
#  - aws configure set preview.cloudfront true
#  - aws cloudfront create-invalidation --distribution-id E2SROA59G3YQZ5 --paths '/*'
#  environment:
#    name: production
#  only:
#  - master
#  when: manual
